// <auto-generated />
using System;
using FlightFinderAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightFinderAPI.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20181124034711_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("FlightFinderAPI.Models.Airport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Airport");
                });

            modelBuilder.Entity("FlightFinderAPI.Models.Flight", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Arrives");

                    b.Property<DateTime>("Departs");

                    b.Property<int>("FirstClassPrice");

                    b.Property<int>("FlightNumber");

                    b.Property<string>("From");

                    b.Property<int>("MainCabinPrice");

                    b.Property<string>("To");

                    b.HasKey("ID");

                    b.ToTable("Flight");
                });
#pragma warning restore 612, 618
        }
    }
}
